### ISSUE TITLE
Not getting the others array from the useOnlineCursor() hook

### ISSUE THREAD

**Issue by swatantragoswami09** [yomorun/react-cursor-chat#32]
hi 
I am using this react-cursor-chat library in react application but not getting the others array from the useOnlineCursor hook 

`import CursorChat, {
  useOnlineCursor,
  useRenderPosition,
} from "@yomo/react-cursor-chat";

const { me, others } = useOnlineCursor({
    presenceURL: "https://prsc.yomo.dev",
    presenceAuthEndpoint: "/api/auth",
    avatar:
      "https://cursor-chat-example.vercel.app/_next/image?url=%2Flogo.png&w=256&q=75",
    name: user.displayName,
  });`

I am not getting the others online users 

![Screenshot (35)](https://user-images.githubusercontent.com/54662673/194910184-4b24ec78-4680-48fe-b31e-a205fe2a1633.png)
![Screenshot (36)](https://user-images.githubusercontent.com/54662673/194910193-fe3b81b0-f6d5-4352-876d-804fac97a6cb.png)

**Comment by luzhenqian** [comment]
#33

**Comment by luzhenqian** [comment]
try updating to version 0.17.0+. @swatantragoswami09

**Comment by swatantragoswami09** [comment]
are you working about react-cursor-chat library version ??
![image](https://user-images.githubusercontent.com/54662673/195298880-abcae3c8-585b-4d22-be98-a94f4669f624.png)

**Comment by luzhenqian** [comment]
![image](https://user-images.githubusercontent.com/33050549/195504082-226b5d75-ec81-4b4e-9ca7-50ed7071b88d.png)
![image](https://user-images.githubusercontent.com/33050549/195504830-db51882b-7e49-4166-a8bf-a2325ac18cc6.png)

This doesn't seem to be our problem, check your npm proxy?

**Comment by swatantragoswami09** [comment]
Please tell me where is am wrong
I am following these steps

**1.  npm i @yomo/react-cursor-chat@0.1.7**
**2.  Created App_id & App-secret using this site https://presencejs.yomo.run/**
**3.  Created one auth.js file and add the app_id & app_secret**
**4.  import CursorChat, { useOnlineCursor, useRenderPosition,} from "@yomo/react-cursor-chat";**
5.  
```
const { me, others } = useOnlineCursor({
            presenceURL: "https://prsc.yomo.dev",
            presenceAuthEndpoint: "/api/auth",
            avatar:
              "https://cursor-chat-example.vercel.app/_next/image?url=%2Flogo.png&w=256&q=75",
            name: user.displayName,
          });
```

**6.  console.log(me) console.log(others)**
1.
![image](https://user-images.githubusercontent.com/54662673/195511025-1dcf81b2-64f1-4f4f-891c-079adce8aad6.png)

2. 
 ![image](https://user-images.githubusercontent.com/54662673/195509858-6eac274f-b363-47d2-a6cb-fbcae34a47fd.png)
3.
 ![image](https://user-images.githubusercontent.com/54662673/195509934-f7211835-4d0f-4648-b8a3-31b26fa308b8.png)
4. 
  ![image](https://user-images.githubusercontent.com/54662673/195509996-99803e27-79b5-491c-acee-a316f0006fda.png)
5.
![image](https://user-images.githubusercontent.com/54662673/195510757-4d927c1b-ed5a-4eba-9d7e-f9332776441d.png)

**Comment by luzhenqian** [comment]
> 请告诉我哪里出了问题 我正在按照这些步骤操作
> 
> **1. npm i @yomo/react-cursor-chat@ 0.1.7 2. 使用此站点****https://presencejs.yomo.run/** **创建 App_id & App-secret [](https://presencejs.yomo.run/)** **3. 创建一个 auth.js 文件并添加 app_id & app_secret ** **4. import CursorChat, { useOnlineCursor, useRenderPosition,} from "@yomo/react-cursor-chat"; ** 5.
> 
> ```
> const { me, others } = useOnlineCursor({
>             presenceURL: "https://prsc.yomo.dev",
>             presenceAuthEndpoint: "/api/auth",
>             avatar:
>               "https://cursor-chat-example.vercel.app/_next/image?url=%2Flogo.png&w=256&q=75",
>             name: user.displayName,
>           });
> ```
> 
> **6. console.log(me) console.log(others)** 0。 ![图片](https://user-images.githubusercontent.com/54662673/195512807-bb16394b-e7ae-4bf9-b77f-038d0d307ae8.png)
> 
> 
> ![图片](https://user-images.githubusercontent.com/54662673/195511025-1dcf81b2-64f1-4f4f-891c-079adce8aad6.png)
> 
> 
> ![图片](https://user-images.githubusercontent.com/54662673/195509858-6eac274f-b363-47d2-a6cb-fbcae34a47fd.png) 3. 4. 5. ![图片](https://user-images.githubusercontent.com/54662673/195509934-f7211835-4d0f-4648-b8a3-31b26fa308b8.png) ![图片](https://user-images.githubusercontent.com/54662673/195509996-99803e27-79b5-491c-acee-a316f0006fda.png) ![图片](https://user-images.githubusercontent.com/54662673/195510757-4d927c1b-ed5a-4eba-9d7e-f9332776441d.png)

Cursor Component and useOnlineCursor cannot be used at the some time.
Cursor Component is out of the box, useOnlineCursor is used to customize cursor logic.
You need to open this page in another tab to have others.

**Comment by swatantragoswami09** [comment]
I am opening it to multiple screens but not getting the data into other arrays.

**Comment by luzhenqian** [comment]
> I am opening it to multiple screens but not getting the data into other arrays.

I wrote an example for you, see here: https://codesandbox.io/s/objective-grass-04xewz?file=/src/App.js

**Comment by swatantragoswami09** [comment]
My backend is working fine
![image](https://user-images.githubusercontent.com/54662673/195542116-90fcfbc3-42a0-4904-86f4-9e917417aac1.png)
![image](https://user-images.githubusercontent.com/54662673/195542320-c72b05ef-fe17-4a71-b565-c4c1e4b39378.png)
![image](https://user-images.githubusercontent.com/54662673/195542405-6f3a3739-3f36-411d-abf8-388fce52f7ba.png)
but still not getting the array object

**Comment by luzhenqian** [comment]
I guess it should be your local version of react-cursor-chat, because it works fine on codesandbox.

**Comment by luzhenqian** [comment]
You can go into the project's node_modules and check if the version is 0.1.7.

**Comment by swatantragoswami09** [comment]
I install 0.1.7 version but not getting the others array still
![image](https://user-images.githubusercontent.com/54662673/195553073-3292b8aa-d8fd-429e-9bb2-b5e74485841e.png)

**Comment by luzhenqian** [comment]
https://codesandbox.io/s/objective-grass-04xewz?file=/src/App.js
Does this code work properly?

**Comment by swatantragoswami09** [comment]
No
![image](https://user-images.githubusercontent.com/54662673/195576342-a5da2eac-bb5a-446c-9601-0795e37c2213.png)

**Comment by luzhenqian** [comment]
![image](https://user-images.githubusercontent.com/33050549/195579839-e14ba076-29e3-4af2-af56-f143fc98ac38.png)
Very strange, I am running normally here.
Sorry, I can't find where the problem is at the moment.

**Comment by swatantragoswami09** [comment]
can you please share with me the backend API file where the endpoint is defined?

**Comment by luzhenqian** [comment]
ok.

```js
export default async function handler(req, res) {
  if (req.method === 'GET') {
      try {
          const response = await fetch('https://prsc.yomo.dev/api/v1/auth', {
              method: 'POST',
              headers: {
                  'Content-Type': 'application/json',
              },
              body: JSON.stringify({
                  app_id: process.env.APP_ID,
                  app_secret: process.env.APP_SECRET,
              }),
          });
          const data = await response.json();
          const token = data.data;
          if (token) {
              res.status(200).json(token);
          } else {
              res.status(400).json({ msg: data.message });
          }
      } catch (error) {
          if (typeof error === 'string') {
              res.status(500).json({ msg: error });
          } else if (error instanceof Error) {
              res.status(500).json({ msg: error.message });
          }
      }
  } else {
      // Handle any other HTTP method
  }
}
```

**Comment by swatantragoswami09** [comment]
why i am not getting the others array data ??
![image](https://user-images.githubusercontent.com/54662673/195768249-e774707f-ce71-4e1f-b2fb-4ea8b357bd0f.png)

**Comment by swatantragoswami09** [comment]
hi I am get the data from the backend but not getting the data into the others array object please help me
![image](https://user-images.githubusercontent.com/54662673/195786893-67ad1b2c-0f13-43f6-aebc-b4b65b8a22d7.png)

**Comment by luzhenqian** [comment]
I'm looking for other colleagues to help check for problems.
You can check if your network has a proxy turned on. web transport doesn't support things like proxies or vpns.

**Comment by swatantragoswami09** [comment]
I am not using any proxy or VPN.

**Comment by swatantragoswami09** [comment]
Finnaly I get the data I don't know the solution but it is showing me the data.
![image](https://user-images.githubusercontent.com/54662673/195804507-94e4d530-3192-4e7e-85eb-b0845faeca0e.png)

**Comment by luzhenqian** [comment]
ok, I'm guessing it might be a network problem.
Please upgrade to version 0.18.0, The version solves the problem in the picture.
